#!/usr/bin/env python3
"""
公開時に index.html へ「キャッシュ対策・自動更新・版数表示」コードを自動挿入する。
GitHub Actions のビルド中だけ実行され、リポジトリ本体（あなたがアップした元ファイル）は
書き換えない。バージョン番号はビルド日時から自動生成するので、手動で番号を上げる必要はない。

使い方:  python3 inject.py <VERSION>
"""
import sys
import re

VERSION = sys.argv[1] if len(sys.argv) > 1 else "dev"
PATH = "index.html"

START = "<!-- AUTO-UPDATE:START (auto-generated by GitHub Actions / do not edit) -->"
END = "<!-- AUTO-UPDATE:END -->"

s = open(PATH, encoding="utf-8").read()

# 既存の自動挿入ブロックがあれば除去（冪等にするため）
s = re.sub(re.escape(START) + r".*?" + re.escape(END) + r"\n?", "", s, flags=re.S)

block = START + """
<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<script>
/* この版数はビルド日時から自動生成（手動で上げる必要なし） */
const APP_VERSION = '__VERSION__';
(function(){
  function ready(f){ if(document.body) f(); else document.addEventListener('DOMContentLoaded', f); }
  /* 右下に版数バッジを表示 */
  ready(function(){
    var b=document.createElement('div'); b.textContent='v'+APP_VERSION;
    b.style.cssText='position:fixed;right:6px;bottom:6px;z-index:9999;font-size:11px;'
      +'color:#8a877f;background:rgba(255,255,255,.85);padding:2px 6px;'
      +'border:1px solid #e4e0d6;border-radius:6px;font-family:system-ui;pointer-events:none';
    document.body.appendChild(b);
  });
  /* Webで開いた場合：最新版を確認し、古ければ自動で切り替え */
  if(location.protocol==='http:'||location.protocol==='https:'){
    fetch(location.pathname+'?_='+Date.now(),{cache:'no-store'})
      .then(function(r){ return r.ok ? r.text() : Promise.reject(); })
      .then(function(t){
        var m=t.match(/APP_VERSION\\s*=\\s*['"]([^'"]+)['"]/); if(!m) return;
        if(m[1]===APP_VERSION) return;
        if(location.search.indexOf('v='+m[1])===-1){
          location.replace(location.pathname+'?v='+encodeURIComponent(m[1]));
        }
      })
      .catch(function(){});
  }
})();
</script>
""" + END

block = block.replace("__VERSION__", VERSION)

anchor = '<meta charset="utf-8">'
if anchor not in s:
    raise SystemExit('charset メタタグが見つかりません: ' + anchor)
s = s.replace(anchor, anchor + "\n" + block, 1)

open(PATH, "w", encoding="utf-8").write(s)
print("injected APP_VERSION =", VERSION)
